TARGET: mobula_op
BUILD_PATH: build
MAX_BUILDING_WORKER_NUM: 8

DEBUG: 0
USING_OPENMP: 0
USING_CBLAS: 0
HOST_NUM_THREADS: 0 # 0 : auto
USING_HIGH_LEVEL_WARNINGS: 1
USING_OPTIMIZATION: 1
USING_ASYNC_EXEC: 0
MXNET_GCC_VERSION: 4

CXX: g++
NVCC: nvcc
HIPCC: hipcc
CUDA_DIR: /opt/cuda
HIP_DIR: /opt/rocm/hip
