TARGET: mobula_op
BUILD_PATH: build
MAX_BUILDING_WORKER_NUM: 8

DEBUG: False
USING_OPENMP: False
USING_CBLAS: False
HOST_NUM_THREADS: 0 # 0 : auto
USING_HIGH_LEVEL_WARNINGS: 1
USING_OPTIMIZATION: 1

CXX: g++
NVCC: nvcc
HIPCC: hipcc
CUDA_DIR: /opt/cuda
HIP_DIR: /opt/rocm/hip
